### ISSUE TITLE
Question: Corrupted local .git, when gmt-docker-compose is used?

### ISSUE THREAD

**Issue by kmlTE** [RADON-SODALITE/hybrid-compute-profile#1]
Hi, @pjakovits, @miwurster, @v-yussupov,

I am facing an issue of building CSAR using GMT built with [gmt-docker-compose](https://github.com/RADON-SODALITE/radon-particles/blob/master/gmt-docker-compose.yml): it throws "500 - Internal Server Error" with "java.lang.NullPointerException".

Looking at the [Jenkins file](https://github.com/RADON-SODALITE/radon-particles/blob/master/Jenkinsfile#L29) as an example, it can be resolved by adding full permissions to all users for the whole repository, however, this screws up local .git, as it is not possible to perform any git actions later on. A possible reason is that GMT container internally modifies .git as a winery user, e.g.:

```bash
$ git status
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean

$ export GMT_COMPOSE_FILE='gmt-docker-compose.yml'
$ export GMT_HTTP_PORT="18090"
$ export PARTICLES_EXPORT_URL="http://127.0.0.1:${GMT_HTTP_PORT}/winery/servicetemplates"
$ export NAMESPACE=radon.blueprints
$ export SERVICE_TEMPLATE="ThumbnailGeneration"
$ export CSAR="${NAMESPACE}.${SERVICE_TEMPLATE}.csar"

$ chmod -R a+rwx .
$ docker-compose -f ${GMT_COMPOSE_FILE} up -d
$ bash -c "curl -H 'Accept: application/xml' -o \"${CSAR}\" \"${PARTICLES_EXPORT_URL}/${NAMESPACE}/${SERVICE_TEMPLATE}/?yaml&csar\""

$ git status
warning: unable to access '.git/config': Permission denied
fatal: unable to access '.git/config': Permission denied
```

Do you have any suggestions of how to use GMT with docker-compose and without changing permissions for the repo files?

**Comment by pjakovits** [comment]
I typically do not use docker compose, but rather the docker commands from the Radon GMT tutorial:
https://winery.readthedocs.io/en/latest/user/getting-started.html

There's one option to use an external folder to keep the node type definitions. And can also map the user id's to avoid user id conflicts:

```
docker run -it -p 8080:8080 \
  -e PUBLIC_HOSTNAME=localhost \
  -e WINERY_FEATURE_RADON=true \
  -e WINERY_REPOSITORY_PROVIDER=yaml \
  -v <path_on_your_host>:/var/repository \
  -u `id -u` \
  opentosca/radon-gmt
```

**Comment by pjakovits** [comment]
When copying node types inside the GMT interface, new folders are created and Winery will do some local commits automatically.
