### ISSUE TITLE
Are node type changes required?

### ISSUE THREAD

**Issue by miwurster** [RADON-SODALITE/hybrid-compute-profile#7]
Hi @kmlTE , in one of the last calls I understood that you had to apply some fixes to the CSAR we provided. Could you quickly highlight what kind of changes/fixes were required? I wonder if we have to update/adjust the node types in `radon-particles` w.r.t. your fixes.

**Comment by kmlTE** [comment]
Hi, @miwurster. Sorry for responding late. Wrt the node_types, the changes are basically providing default empty string values for properties that were not possible in the earlier version of GMT. In particular in:
```
- nodetypes/sodalite.nodes.OpenStack/VM/NodeType.tosca: userdata
- nodetypes/sodalite.nodes/DockerRegistry/NodeType.tosca: docker_user, docker_pass
```

**Comment by miwurster** [comment]
Thanks @kmlTE. Updated the PR.
